export type {
  HeaderNavItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
} from "./settings-types";
import type {
  HeaderNavItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
} from "./settings-types";

export const settings = {
  colorScheme: "Default Dark",
  colorMode: {
    defaultMode: "dark",
    lightScheme: "Default Light",
    darkScheme: "Default Dark",
    respectPrefersColorScheme: true,
  } as ColorModeConfig | false,
  siteName: "zudo-pattern-gen",
  siteDescription: "Generate deterministic visual patterns from text seeds — 30 algorithms from geometric tiles to noise-based textures" as string,
  base: "/pj/pattern-gen/doc/",
  trailingSlash: false as boolean,
  noindex: false as boolean,
  editUrl: false as string | false,
  siteUrl: "" as string,
  docsDir: "src/content/docs",
  locales: {} as Record<string, LocaleConfig>,
  mermaid: false,
  sitemap: false,
  docMetainfo: true,
  docTags: false,
  llmsTxt: false,
  math: false,
  aiAssistant: false as boolean,
  docHistory: false,
  colorTweakPanel: false as boolean,
  htmlPreview: undefined as HtmlPreviewConfig | undefined,
  versions: false as VersionConfig[] | false,
  claudeResources: false as { claudeDir: string; projectRoot?: string } | false,
  footer: {
    links: [],
    copyright: 'Copyright &copy; 2026 <a href="https://x.com/Takazudo">Takazudo</a>. Built with <a href="https://takazudomodular.com/pj/zudo-doc">zudo-doc</a>.',
  } satisfies FooterConfig as FooterConfig | false,
  githubUrl: "https://github.com/Takazudo/zudo-pattern-gen" as string | false,
  appUrl: "https://zudo-pattern-gen.pages.dev/pj/pattern-gen/" as string | false,
  headerNav: [
    { label: "Getting Started", path: "/docs/getting-started", categoryMatch: "getting-started" },
    { label: "Patterns", path: "/docs/patterns", categoryMatch: "patterns" },
    { label: "API", path: "/docs/api", categoryMatch: "api" },
  ] satisfies HeaderNavItem[],
};
