# Cloudflare Pages project configuration

compatibility_date = "2024-12-01"
pages_build_output_dir = "./packages/pattern-gen-viewer/dist"

[vars]
AUTH0_DOMAIN = "placeholder.us.auth0.com"
AUTH0_CLIENT_ID = "placeholder"

[[d1_databases]]
binding = "DB"
database_name = "zudo-pattern-gen"
database_id = "placeholder"

[[r2_buckets]]
binding = "FILES"
bucket_name = "zudo-pattern-gen-files"
