export type {
  HeaderNavItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
} from './settings-types';
import type {
  HeaderNavItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
} from './settings-types';

export const settings = {
  colorScheme: 'Default Dark',
  colorMode: false as ColorModeConfig | false,
  siteName: 'Pattern Gen Styleguide',
  siteDescription: 'Component catalog and design token reference.' as string,
  base: process.env.STYLEGUIDE_BASE || '/pj/pattern-gen/styleguide/',
  trailingSlash: false as boolean,
  docsDir: 'src/content/docs',
  locales: {} satisfies Record<string, LocaleConfig>,
  mermaid: false,
  noindex: false as boolean,
  editUrl: false as string | false,
  siteUrl: '' as string,
  sitemap: false,
  docMetainfo: false,
  docTags: false,
  llmsTxt: false,
  math: false,
  onBrokenMarkdownLinks: 'warn' as 'warn' | 'error' | 'ignore',
  aiAssistant: false as boolean,
  colorTweakPanel: true as boolean,
  docHistory: false,
  htmlPreview: undefined as HtmlPreviewConfig | undefined,
  versions: false as VersionConfig[] | false,
  claudeResources: false as { claudeDir: string; projectRoot?: string } | false,
  footer: false as FooterConfig | false,
  sidebarFilter: true,
  headerNav: [
    { label: 'Design System', path: '/tokens', categoryMatch: 'tokens' },
    { label: 'Components', path: '/components', categoryMatch: '!' },
  ] satisfies HeaderNavItem[],
};
